#!/usr/bin/env python3
"""What a note smells of: docs/data/notes2.json

The catalogue names about two thousand notes and nobody can hand-write a line for each, so a note is explained in three steps:
  1. exact:   a sentence written for that very name (the commonest notes, and the odd ones a rule would get wrong);
  2. heads:   the material the name is about. Names are head-final in both languages ("Tunisian Orange Blossom",
              "Sicilya limonu"), so of all materials found in a name the rightmost one wins; "generic" heads (flower, wood,
              fruit ...) are asked only when no material was found;
  3. quals / origins: what is left of the name adds a short clause ("candied", "leaf", "white", "Sicilian").

Patterns are matched against the folded name (ASCII, lower case, punctuation as spaces). In a pattern "a|b c|d+" each
alternative is a whole word or phrase; English words may take a plural s, a trailing + lets Turkish endings follow
(limon+ matches limon, limonu, limonlar), a leading = allows nothing after it, a leading ^ matches only when the
alternative is the whole name ("Milk" is milk, "Almond Milk" is almond).

Run:  python scripts/build_notes.py      then  node scripts/notes_check.js  to see what is still unexplained.
"""
import json, os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT = os.path.join(ROOT, 'docs', 'data', 'notes2.json')
OLD = os.path.join(ROOT, 'docs', 'data', 'notes.json')

TR_END = r'(?:lari|leri|lar|ler|si|su|ni|nu|yi|yu|i|u)?'


def rx(spec):
    alts = []
    for a in spec.split('|'):
        a = a.strip()
        if not a: continue
        whole = a.startswith('^')
        if whole: a = a[1:]
        if a.startswith('='): body, tail = a[1:], ''
        elif a.endswith('+'): body, tail = a[:-1], TR_END
        else: body, tail = a, '(?:e?s)?'
        w = r'\s+'.join(re.escape(x) for x in body.split()) + tail
        alts.append((len(body), '^' + w + '$' if whole else w))
    # a regex takes the first alternative that fits, so the longer phrase has to stand before the word it starts with
    alts = [x[1] for x in sorted(alts, key=lambda x: -x[0])]
    return r'\b(?:' + '|'.join(alts) + r')\b'


# ---------- the material a name is about ----------
HEADS = [
    # citrus
    ('bergamot+', 'Bergamot: Earl Grey çayındaki koku; ferah, hafif acı ve çiçeksi bir narenciye.'),
    ('lemon|limon+|citron lemon', 'Limon: keskin, ekşi ve tertemiz bir ferahlık; açılışta parlar, çabuk uçar.'),
    ('lime|limetta|kaffir lime|finger lime|calamansi|sudachi|hatkora|rangpur|misket limon+|limoncello', 'Misket limonu (lime): limondan daha yeşil, keskin ve hafif acı; kokteyl ferahlığı verir.'),
    ('orange|portakal+|orangewood', 'Portakal: sulu, tatlı ve neşeli bir narenciye; açılışa sıcak bir parlaklık katar.'),
    ('orange blossom|orange flower|portakal cicegi|fleur d oranger|orange flower water|citrus blossom', 'Portakal çiçeği: bal gibi tatlı, temiz ve hafif yeşil bir beyaz çiçek; sabunsu bir ferahlık verir.'),
    ('bitter orange|bigarade|turunc+|chinotto|bigarane|seville orange', 'Turunç (acı portakal): portakalın daha kuru, acımsı ve aromatik hali.'),
    ('blood orange|kan portakal+', 'Kan portakalı: portakalın daha koyu, ahududumsu ve hafif acı türü.'),
    ('mandarin|mandarine|tangerine|clementine|mandalina+|klementin+|mandora|tangelo|satsuma', 'Mandalina: portakaldan daha tatlı, yumuşak ve neşeli bir narenciye.'),
    ('grapefruit|greyfurt+|pomelo|pamplemousse|methyl pamplemousse|graperfuit', 'Greyfurt: ferah, acımsı-ekşi ve hafif kükürtlü; uyandıran bir açılış notası.'),
    ('yuzu|kumquat|kamkat+|citron|agac kavunu|buddha s hand|cedrat|hassaku|kabosu', 'Uzak Doğu narenciyesi: limon ile mandalina arası; aromatik, çiçeksi ve çok ferah.'),
    ('petitgrain', 'Petitgrain: turunç ağacının yaprak ve dallarından; yeşil, odunsu, hafif acı bir narenciye.'),
    ('neroli', 'Neroli: turunç çiçeğinin damıtılmış yağı; ferah, yeşil ve hafif bal tatlılığında.'),
    ('lemongrass|limon otu|citronella|lemon grass', 'Limon otu: limon gibi ama daha otsu ve keskin; ferah, temiz bir yeşillik.'),
    ('verbena|vervain|lemon verbena|mine cicegi', 'Mine çiçeği (verbena): limonlu, yeşil ve çay gibi ferah bir ot kokusu.'),
    ('litsea cubeba|may chang', 'Litsea cubeba: limon şekeri gibi tatlı, yoğun ve ferah bir narenciye yaprağı.'),
    ('lemon balm|melissa|melisa+|ogul otu', 'Melisa (oğul otu): yumuşak limonlu, otsu ve sakinleştirici.'),
    ('citrus|citruses|narenciye+|agrumes|hesperidic', 'Narenciye akoru: limon, portakal ve bergamot karışımı ferah, parlak bir açılış.'),
    # fruit
    ('apple|elma+|applejack', 'Elma: sulu, gevrek ve tatlı-ekşi; şampuan temizliğinde bir tazelik katar.'),
    ('pear|armut+|nashi|nashi pear', 'Armut: sulu, tatlı ve hafif çiçeksi; yumuşak, modern bir meyve notası.'),
    ('peach|seftali+|nectarine|nektarin+', 'Şeftali: kadifemsi, sulu ve kremsi tatlı; ten gibi yumuşak bir meyve.'),
    ('apricot|kayisi+', 'Kayısı: şeftaliden daha ballı ve kuru; süet gibi yumuşak bir meyve.'),
    ('plum|erik+|erigi|mirabelle|mirabella|greengage|damson|prunol|prune|umeshu|wu mei', 'Erik: koyu, şaraplı ve tatlı; meyveye derinlik ve olgunluk katar.'),
    ('cherry|cherries|kiraz+|visne+|griotte|maraschino|morello', 'Kiraz / vişne: tatlı-ekşi, bademsi ve likör gibi; çekici ve oyuncu.'),
    ('strawberry|strawberries|cilek+|cilegi|fraise|gariguette', 'Çilek: tatlı, sulu ve şeker gibi; genç ve neşeli bir meyve.'),
    ('raspberry|raspberries|ahududu+|framboise', 'Ahududu: ekşi-tatlı, canlı ve hafif menekşemsi bir kırmızı meyve.'),
    ('blackberry|blackberries|bogurtlen+|mulberry|dut+|boysenberry|loganberry|tayberry|dewberry|cloudberry|arctic bramble|bramble',
     'Böğürtlen / dut: koyu, şaraplı ve hafif miskli bir orman meyvesi.'),
    ('blueberry|blueberries|yaban mersini|bilberry|huckleberry', 'Yaban mersini: tatlı, hafif ekşi ve reçelimsi mavi meyve.'),
    ('black currant|blackcurrant|cassis|frenk uzumu|currant|red currant|white currant|currant bud', 'Frenk üzümü (cassis): ekşi, yeşil ve keskin bir meyve; hafif kedi otu sertliği vardır.'),
    ('cranberry|cranberries|turna yemisi|lingonberry|goji|goji berries|acai|acai berry|maqui berry|sea buckthorn|barberry|elderberry|winterberry|snowberry|bearberry|wolfberry|goldenberry|miracle berry|gooseberry|rose hip|kusburnu+|rowan|sumac|acerola',
     'Ekşi orman meyvesi: canlı, mayhoş ve hafif buruk; kırmızı meyve parlaklığı verir.'),
    ('berries|berry|red fruit|red berries|kirmizi meyve+|forest fruit|yaban meyveleri|wild berries|berry fruit|fruits rouges', 'Kırmızı / orman meyveleri: çilek, ahududu ve böğürtlen karışımı tatlı-ekşi bir akor.'),
    ('grape|uzum+|raisin|kuru uzum+|muscat grape', 'Üzüm: sulu, tatlı ve şaraba yakın; kurusu ballı ve koyudur.'),
    ('fig|incir+|fig tree|fig milk|fig nectar', 'İncir: sütlü, yeşil ve tatlı; yaprağı yeşil-acımsı, meyvesi ballıdır.'),
    ('pineapple|ananas+', 'Ananas: sulu, ekşi-tatlı ve tropik; açılışa parlak, neşeli bir hava verir.'),
    ('mango', 'Mango: olgun, kremsi ve tropik tatlı; kabuğunda hafif reçinemsi bir yeşillik vardır.'),
    ('coconut|hindistan cevizi|coco|coco de mer|coconut water|coconut milk|coconut nectar|coconut powder|hindistan cevizi sutu',
     'Hindistan cevizi: kremsi, sütlü ve tatlı; güneş kremi ve tatil hissi verir.'),
    ('banana|muz+|plantain', 'Muz: kremsi, tatlı ve yumuşak bir tropik meyve.'),
    ('melon|kavun+|cantaloupe|honeydew|honeydew melon', 'Kavun: sulu, serin ve hafif tatlı; su notalarıyla ferah bir his.'),
    ('watermelon|karpuz+', 'Karpuz: sulu, serin ve şeker gibi hafif; yaz ferahlığı.'),
    ('pomegranate|nar+|grenadine', 'Nar: ekşi-tatlı, canlı ve hafif buruk bir kırmızı meyve.'),
    ('lychee|litchi|lici+|rambutan|longan|longan berries', 'Liçi: gül gibi kokan sulu, tatlı ve ferah bir egzotik meyve.'),
    ('passion fruit|passionfruit|carkifelek meyvesi|maracuja|granadilla', 'Çarkıfelek meyvesi: ekşi, tropik ve keskin; hafif kükürtlü bir parlaklığı vardır.'),
    ('guava|papaya|pitahaya|dragon fruit|star fruit|carambola|kiwi|persimmon|jackfruit|durian|soursop|cherimoya|sapodilla|mamey|lucuma|feijoa|feijoa fruit|pitanga|jabuticaba|cupuacu|tamarind|mangosteen|star apple|salak|hog plum|seriguela|medlar|loquat|japanese loquat|jujube|quandong|akebia fruit|black sapote|buriti|tucuma|genipapo|bael|ground cherry|prickly pear|cactus fruit|ube|taro|purple yam',
     'Egzotik meyve: sulu, tatlı ve tropik; parfüme tatil havası ve canlılık katar.'),
    ('quince|ayva+', 'Ayva: elma ile armut arası; ballı, buruk ve hafif çiçeksi.'),
    ('rhubarb|ravent+|rhuburb', 'Ravent: ekşi, yeşil ve gevrek; çilek sapı gibi mayhoş bir tazelik.'),
    ('=date|dates|hurma+', 'Hurma: koyu, ballı ve karamelimsi bir kuru meyve; Doğu tatlılığı.'),
    ('dried fruit|kuru meyve+|dried plum|dried apricot|candied fruit|fruit confit', 'Kuru meyve: yoğun, ballı ve şaraplı; sıcak ve olgun bir tatlılık.'),
    ('olive|zeytin+|olive tree', 'Zeytin: yeşil, hafif tuzlu ve yağlı; Akdeniz havası verir.'),
    ('tomato|domates+|tomato leaf', 'Domates yaprağı: keskin yeşil; toprak ve bahçe kokusu.'),
    ('tropical fruit|tropical|tropik+|exotic fruit|hawaiian fruits|cocktail fruits|fruit salad', 'Tropik meyveler: mango, ananas ve çarkıfelek gibi sulu, güneşli bir karışım.'),
    # flowers
    ('rose|gul+|rosebud|rosa|eglantine|rose petal|gul yapraklari|rose water|rose oil|tea rose|rose de mai', 'Gül: çiçeklerin kraliçesi; taze, ballı, hafif limonlu ya da baharatlı olabilir.'),
    ('jasmine|jasmin|yasemin+|sambac|melati', 'Yasemin: yoğun, sıcak ve baygın bir beyaz çiçek; hafif hayvansı bir derinliği vardır.'),
    ('tuberose|sumbulteber+|tubereuse', 'Sümbülteber: kremsi, yoğun ve baş döndürücü beyaz çiçek; tereyağımsı ve tatlı.'),
    ('gardenia|gardenya+', 'Gardenya: kremsi, mantarımsı-yeşil ve yoğun bir beyaz çiçek.'),
    ('ylang|ylang ylang|cananga', 'Ylang-ylang: muzumsu, kremsi ve egzotik sarı çiçek; tatlı ve sıcak.'),
    ('lily of the valley|muguet|muge+|lilybelle|lily of the valley leaves', 'Müge: taze, yeşil ve sabunsu; bahar temizliği veren narin bir çiçek.'),
    ('lily|lilies|zambak+|zambagi|lilium', 'Zambak: yeşil-baharatlı, mumsu ve görkemli bir beyaz çiçek.'),
    ('water lily|nilufer+|lotus|nelumbo|water hyacinth|water flower|water flowers|aquatic flowers', 'Nilüfer / lotus: sulu, serin ve hafif tatlı; gölet ferahlığı veren su çiçeği.'),
    ('iris|orris|susen+|iris butter|iris root|orris root|iris pallida|iris flower|diviniris', 'İris (süsen kökü): pudralı, havuçsu-topraksı ve serin; ruj ve pudra şıklığı.'),
    ('violet|menekse+|violette|parma violet', 'Menekşe: pudralı, tatlı ve hafif odunsu; şekerleme ve ruj kokusu.'),
    ('violet leaf|violet leaves|menekse yapragi', 'Menekşe yaprağı: yeşil, salatalığımsı ve sulu-metalik; çiçeğinden çok farklıdır.'),
    ('peony|peonies|sakayik+|sakayigi', 'Şakayık: taze, gül gibi ama daha sulu ve hafif; temiz bir bahar çiçeği.'),
    ('freesia|frezya+', 'Frezya: taze, biberimsi ve sabunsu; hafif, temiz bir çiçek.'),
    ('magnolia|manolya+|champaca|campaka+|michelia|magnolan', 'Manolya / champaca: limonlu-kremsi, hafif meyveli bir beyaz çiçek.'),
    ('lilac|leylak+|leylagi', 'Leylak: bahar havası; pudralı, yeşil ve hafif bademsi bir çiçek.'),
    ('hyacinth|sumbul+|hiacynth', 'Sümbül: yeşil, sulu ve keskin bahar çiçeği; toprak ve sap kokusu taşır.'),
    ('narcissus|nergis+|daffodil|jonquil|jonquille', 'Nergis: yeşil, samansı ve hafif hayvansı; yoğun, bal gibi bir çiçek.'),
    ('mimosa|mimoza+|cassie|acacia|akasya+|black locust|silk tree blossom', 'Mimoza / akasya: pudralı, ballı ve bademsi sarı çiçek; yumuşak ve güneşli.'),
    ('heliotrope|heliotrop+', 'Heliotrop: bademli, vanilyalı ve pudralı; oyun hamuru yumuşaklığı.'),
    ('orchid|orkide+', 'Orkide: parfümde hayali bir akor; kremsi, vanilyamsı ve egzotik bir çiçek hissi.'),
    ('carnation|karanfil cicegi|dianthus|fringed pink', 'Karanfil çiçeği: baharatlı, pudralı ve sıcak bir çiçek.'),
    ('geranium|sardunya+|pelargonium|rose geranium', 'Sardunya: gül gibi ama daha yeşil, naneli ve limonlu.'),
    ('lavender|lavanta+|lavandin', 'Lavanta: temiz, aromatik ve hafif tatlı; berber ve çamaşır temizliği.'),
    ('osmanthus', 'Osmanthus: kayısı ve süet kokan Uzak Doğu çiçeği; meyvemsi ve çaylı.'),
    ('frangipani|plumeria|tiare|tiare flower|tiare cicegi|monoi|monoi oil', 'Tiare / frangipani: kremsi, hindistan cevizimsi tropik beyaz çiçek; güneş yağı hissi.'),
    ('honeysuckle|hanimeli+', 'Hanımeli: ballı, taze ve hafif narenciyeli; yaz akşamı çiçeği.'),
    ('cyclamen|siklamen+', 'Siklamen: sulu, serin ve hafif yeşil; temiz, şeffaf bir çiçek.'),
    ('chamomile|camomile|papatya+|daisy|daisies', 'Papatya: elmamsı, otsu ve ballı; sakin, çay gibi bir çiçek.'),
    ('hibiscus|hibiskus+', 'Hibiskus: ekşimsi, meyveli ve hafif çiçeksi; kırmızı çay gibi.'),
    ('cherry blossom|sakura|kiraz cicegi', 'Kiraz çiçeği: narin, pudralı ve hafif meyveli; bahar ferahlığı.'),
    ('wisteria|mor salkim+', 'Mor salkım: leylak ile yasemin arası; tatlı, hafif baharatlı bir sarkan çiçek.'),
    ('sweet pea|bezelye cicegi', 'Bezelye çiçeği (sweet pea): narin, ballı ve hafif yeşil; taze, pastel bir çiçek.'),
    ('tulip|lale+', 'Lale: yeşil, sulu ve çok hafif; taze kesilmiş çiçek sapı hissi.'),
    ('poppy|poppies|gelincik+', 'Gelincik: parfümde hayali bir akor; pudralı, hafif yeşil ve ipeksi.'),
    ('marigold|tagetes|kadife cicegi|calendula', 'Kadife çiçeği: keskin yeşil, elmamsı ve hafif acı; meyveye canlılık katar.'),
    ('immortelle|helichrysum|olmez cicek|everlasting', 'Ölmez çiçek: akçaağaç şurubu, köri ve saman arası; sıcak, ballı ve kuru.'),
    ('broom|genet|katirtirnagi|gorse|laburnum|lydia broom', 'Katırtırnağı: ballı, samansı ve hafif deri kokan güneşli sarı çiçek.'),
    ('datura|angels trumpet|angel s trumpet|belladonna|lady of the night flower|night blooming jasmine|night blooming cereus|queen of the night flower|moon flower|moonflower|cestrum',
     'Gece çiçeği: gece açan, yoğun, baygın ve hafif narkotik bir beyaz çiçek.'),
    ('camellia|camelia|kamelya+', 'Kamelya: neredeyse kokusuz bir çiçek; parfümde temiz, çaylı-yeşil bir akor.'),
    ('linden|linden blossom|lime blossom|lime linden blossom|tilleul|ihlamur+|limewood', 'Ihlamur: ballı, yeşil ve çay gibi; yumuşak, sakin bir çiçek.'),
    ('elderflower|murver+|black elder', 'Mürver çiçeği: ballı, misket üzümü gibi ve hafif yeşil; bahar şerbeti.'),
    ('heather|funda+', 'Funda: kuru, ballı ve otsu; bozkır havası.'),
    ('hawthorn|alic+|aubepine', 'Alıç çiçeği: bademli, pudralı ve hafif anasonlu; yumuşak bir bahar çiçeği.'),
    ('pittosporum|pitosporum', 'Pitosporum: yasemin ile portakal çiçeği arası tatlı bir beyaz çiçek.'),
    ('cotton flower|cotton blossom|pamuk cicegi', 'Pamuk çiçeği: temiz, pudralı ve havadar; yeni yıkanmış çamaşır hissi veren hayali bir akor.'),
    ('white flower|white blossom|beyaz cicek+|white floral|creamy flowers', 'Beyaz çiçekler: yasemin, sümbülteber ve portakal çiçeği ailesi; kremsi, yoğun ve baygın.'),
    ('dahlia|gerbera|zinnia|azalea|rhododendron|bougainvillea|hortensia|hydrangea|chrysanthemum|amaryllis|begonia|fuchsia|gladiolus|pansy|primrose|buttercup|wallflower|stephanotis|boronia|mignonette|reseda|snowdrop|bluebell|forget me not|cornflower|periwinkle|aglaia|alstroemeria|protea|strelitzia|lantana|hollyhock|malva|althaea|nasturtium|anemona|phlox|impatiens|petunia|edelweiss|celosia|poinsettia|trillium|viburnum|abelia|daphne|buddleia|jacaranda|oleander|nerium oleander|kadam|calycanthus|mirabilis|portlandia|hoya carnosa|sand lily|karo karounde|karo korund|osmanthus milk|ashoka flower|jade flower|dove tree|skeleton flower|ornithogalum|safflower|goldenrod|dandelion|yarrow|tansy|clover|lupin|thistle|arnica|st john s wort|meadowsweet|gentiana|mahonia|hellebore flower|cosmos flower|nemophila|euphorbia|kowhai|kunzea|manuka|kanuka|monarda|heliconia|flamingo flower|bromelia|crinum lily|daylily|pinwheel flower|jarana flower|gustavia flower|campion flower|rangoon creeper|chimonanthus|wintersweet|honeybush|sunflower|aycicegi|holly|privet|mayflower|starflower|sweet alyssum|baby s breath|borage|can cicegi|blackthorn|tamarisk|field scabious|blue bugle|prunella|rosebay willowherb|lamprocapnos|polygonum|erigeron|mistletoe|arbutus|smoketree|alumroot|solomon s seal|tussilago farfara|butomus umbellatus',
     'Çiçek notası: parfümde çoğu kez hayali bir akor; yumuşak, taze ve hafif tatlı bir çiçek hissi verir.'),
    # green, herbs, aromatics
    ('mint|nane+|peppermint|spearmint|pennyroyal|water mint|apple mint|menthol|mentol+', 'Nane: serin, mentollü ve tertemiz; anında ferahlık verir.'),
    ('basil|feslegen+|tulsi|shiso', 'Fesleğen: yeşil, anasonlu-baharatlı ve taze; Akdeniz mutfağı ferahlığı.'),
    ('rosemary|biberiye+', 'Biberiye: kâfurlu, çamsı ve otsu; temiz, erkeksi bir aromatik.'),
    ('thyme|kekik+|kekigi|oregano|marjoram|mercankosk+|satureja|hyssop|santolina|sideritis', 'Kekik ailesi: sıcak, otsu ve hafif tıbbi; kuru Akdeniz yamaçları.'),
    ('sage|adacayi+|clary sage|misk adacayi|clary|sclarene', 'Adaçayı: otsu ve hafif kâfurlu; misk adaçayında amber ve çay sıcaklığı vardır.'),
    ('artemisia|wormwood|pelin+|pelin otu|absinthe|mugwort|tarragon|tarhun+', 'Pelin / tarhun: acı-yeşil, anasonlu ve keskin; absinthe havası.'),
    ('juniper|juniper berry|juniper berries|ardic+|ardic meyvesi|gin|=cin', 'Ardıç: çamsı, biberli ve ferah; cin içkisinin kokusu.'),
    ('cypress|selvi+|servi+|cupressus|blue cypress', 'Selvi: kuru, çamsı ve hafif dumanlı; Akdeniz ormanı ferahlığı.'),
    ('pine|cam+|fir|koknar+|spruce|ladin+|conifer|evergreen|larch|hemlock|thuja|araucaria|pine needle|pine tree|pine tree needles|christmas tree|sequoia|redwood|tsuga|silver fir|fir balsam|balsam fir',
     'Çam / köknar: reçineli, yeşil ve serin; orman havası.'),
    ('eucalyptus|okaliptus+|camphor|kafur+|tea tree|tea tree oil|cajeput|ravensara|wintergreen', 'Okaliptüs / kâfur: serin, mentollü ve tıbbi-temiz; nefes açan bir ferahlık.'),
    ('galbanum', 'Galbanum: çok keskin yeşil; kırılmış sap, bezelye ve toprak kokusu.'),
    ('hay|saman+|kuru ot+|flouve|sweet grass|deer tongue grass|liatris|liatrix|melilot|melilotus|straw|sweet clover', 'Saman / kuru ot: ballı, tütünsü ve güneşte kurumuş çayır kokusu.'),
    ('grass|cimen+|green grass|cut grass|lawn', 'Çimen: taze kesilmiş, sulu ve yeşil; açık hava hissi.'),
    ('tea|cay+|oolong|matcha|earl grey|rooibos|darjeeling|lapsang souchong|genmaicha|assam|pu er|chai|longjing|yunnan tea|bohea', 'Çay: kuru, hafif buruk ve aromatik; yeşil çay ferah, siyah çay dumanlı, beyaz çay narindir.'),
    ('mate|yerba mate', 'Mate: yeşil, samansı ve hafif dumanlı; tütün ile çay arası.'),
    ('ivy|sarmasik+|sarmasigi', 'Sarmaşık: serin, ıslak ve koyu yeşil yaprak kokusu.'),
    ('bamboo|bambu+', 'Bambu: sulu, yeşil ve hafif odunsu; Uzak Doğu sadeliği.'),
    ('cucumber|salatalik+|salataligi', 'Salatalık: sulu, serin ve yeşil; su notalarına tazelik katar.'),
    ('fern|egrelti+|fougere', 'Eğrelti (fougère): lavanta, meşe yosunu ve kumarin akoru; klasik berber temizliği.'),
    ('moss|yosun+|oakmoss|oak moss|mese yosunu|treemoss|tree moss|lichen|evernyl|veramoss|cedarmoss', 'Meşe yosunu: nemli orman zemini; yeşil-topraksı, hafif tuzlu ve mürekkebimsi bir derinlik.'),
    ('seaweed|algae|deniz yosunu|laminaria|kelp|posidonia|seagrass|red algae|sea daffodil|crithmum|iodine', 'Deniz yosunu: tuzlu, iyotlu ve yeşil; gerçek deniz kıyısı kokusu.'),
    ('vetiver|vetyver', 'Vetiver: kök kokusu; kuru, topraksı, dumanlı ve hafif greyfurtlu bir odunsu.'),
    ('patchouli|paculi+|patchouly', 'Paçuli: nemli toprak, kakao ve odun arası; koyu, tatlımsı ve kalıcı.'),
    ('angelica|melek otu', 'Melek otu: yeşil, misk gibi ve biberimsi bir kök kokusu.'),
    ('fennel|rezene+|anise|aniseed|anason+|star anise|dill|dereotu+|licorice|liquorice|meyan+|meyan koku|caraway|karaman kimyonu|ouzo|raki|sambuca|pastis',
     'Anason ailesi: tatlı, meyan köklü ve ferah-baharatlı.'),
    ('coriander|kisnis+|cilantro', 'Kişniş: narenciyeli, biberimsi ve sabunsu ferah bir baharat.'),
    ('celery|kereviz+|lovage|parsley|maydanoz+|watercress', 'Kereviz / maydanoz: yeşil, tuzlu-otsu ve keskin bir sebze notası.'),
    ('carrot|havuc+|carrot seed|havuc tohumu', 'Havuç tohumu: topraksı, irisimsi ve hafif tatlı; pudralı bir kök kokusu.'),
    ('hemp|kenevir+|cannabis|marijuana', 'Kenevir: yeşil, reçineli ve hafif tatlı otsu koku.'),
    ('tobacco|tabacco|tutun+|tabac|cigar|cigarette|puro+|hookah|shisha|nargile+|naswar', 'Tütün: kurutulmuş yaprak; ballı, samansı, hafif dumanlı ve sıcak.'),
    ('davana', 'Davana: kuru meyve ve likör kokan Hint otu; tatlı, otsu ve hafif şaraplı.'),
    ('nettle|isirgan+|tomato leaf|rhubarb leaf|fig leaf|incir yapragi|green fig', 'Yeşil yaprak: ezilmiş yaprağın keskin, sütlü-yeşil ve hafif acı kokusu.'),
    ('massoia|massoia wood|massioa', 'Massoia: hindistan cevizi ve süt kokan kremsi bir ağaç kabuğu.'),
    ('ginseng|valerian|hops|henna|guarana|coca|kudzu|sarsaparilla|catnip|rue|khella|centella asiatica|turnera diffusa|argan|avocado|pandanus|flax|reed|bulrush|pollen|wasabi|caper|asafoetida|pataqueira|paramela|capitiu|maninka|cyperus esculentus|dyer s greenweed|ocotea quixos|cascarilla|bushman candle|longoza|sugandha kokila|portulaca|pigweed|tamanu|breadnut|myrica|andiroba|peyote|rumex|nalca|calafate|kumbaru|ducke|western skunk cabbage|laurissilva forest|nom maew',
     'Bitki notası: bir ot, kök ya da tohumun özütü; yeşil, otsu ve hafif topraksı bir doğallık katar.'),
    # spices
    ('pepper|biber+|black pepper|karabiber+|white pepper|green pepper|peppercorn|cubeb|betel pepper|madagascar pepper|pepper oil|peppertree|pepperwood',
     'Biber: kuru, keskin ve ferah bir baharat; parfüme canlılık ve hafif bir odunsuluk verir.'),
    ('pink pepper|pembe biber+|baie rose|rose pepper|pink peppercorn', 'Pembe biber: gül ve meyve kokan hafif, parlak bir biber; açılışa ışıltı verir.'),
    ('sichuan pepper|szechuan pepper|sichuan biberi|timur|sansho|japanese pepper', 'Sichuan / timur biberi: greyfurt gibi narenciyeli, karıncalandıran ferah bir biber.'),
    ('chili|chilli|chili pepper|red chilli pepper|pimento|pimiento|paprika|red pepper|kirmizi biber+|aci biber+|carolina reaper|cayenne|green bell pepper|sweet pepper',
     'Acı / kırmızı biber: sıcak, yakıcı ve hafif tatlı; parfüme ateş katar.'),
    ('cardamom|kakule+|cardamon', 'Kakule: serin, limonlu-okaliptüslü ve hafif tatlı bir baharat; kahveye çok yakışır.'),
    ('cinnamon|tarcin+|cassia|cinammon|canelle', 'Tarçın: sıcak, tatlı ve hafif yakıcı; kış ve tatlı çağrışımı.'),
    ('clove|karanfil+|eugenol|clove leaf', 'Karanfil (baharat): sıcak, keskin ve hafif tıbbi-tatlı.'),
    ('nutmeg|muskat+|mace|muskat cicegi', 'Muskat: sıcak, kuru ve odunsu-tatlı bir baharat; erkeksi parfümlerin klasik eşlikçisi.'),
    ('ginger|zencefil+|galangal|galanga|ginger flower|alpinia', 'Zencefil: limonlu, sabunsu ve hafif yakıcı; taze ve enerjik bir baharat.'),
    ('saffron|safran+|safraleine', 'Safran: derimsi, ballı ve hafif metalik-ilaçsı; lüks, kuru bir baharat.'),
    ('cumin|kimyon+', 'Kimyon: sıcak, terli-hayvansı ve topraksı bir baharat; tene yakın bir sıcaklık.'),
    ('vanilla|vanilya+|vanillin|ethylvanillin|vanille|vanilla bean|vanilla pod|vanilya cubugu|vanilla caviar', 'Vanilya: tatlı, kremsi ve sıcak; sarmalayıcı ve rahatlatıcı.'),
    ('tonka|tonka bean|tonka fasulyesi|coumarin|kumarin+|tonquitone', 'Tonka fasulyesi: bademli, vanilyalı ve samansı bir tatlılık; kumarin kokusu.'),
    ('allspice|yenibahar+|pimento berries|pimento seeds|pimento leaf', 'Yenibahar: karanfil, tarçın ve biber karışımı gibi sıcak bir baharat.'),
    ('turmeric|zerdecal+|curry|kori+|masala|curry tree|fenugreek', 'Zerdeçal / köri: topraksı, sıcak ve hafif acı sarı baharat.'),
    ('bay|bay leaf|defne+|laurel|defne yapragi|bay essence', 'Defne: yeşil, kâfurlu ve baharatlı yaprak; tıraş losyonu klasiği.'),
    ('sesame|susam+', 'Susam: kavrulmuş, yağlı ve fındıksı; sıcak, lezzetli bir not.'),
    # woods
    ('sandalwood|sandal|sandal agaci|santal|sandalwood flower', 'Sandal ağacı: kremsi, sütlü ve yumuşak bir odun; sıcak, sakin ve kalıcı.'),
    ('cedar|sedir+|cedarwood|cedre|cedar leaves|cedar needles', 'Sedir: kuru, kalem talaşı gibi temiz bir odun; parfüme iskelet verir.'),
    ('oud|=ud|udu|agarwood|aoud|oudh|kyara|jinko|oud wood', 'Ud: reçineli, koyu ve hayvansı-dumanlı bir odun; Doğu’nun en değerli kokusu.'),
    ('guaiac|guaiac wood|gayak+|gayak agaci|gaiac|gaiac wood|guayacan|palo santo', 'Gayak / palo santo: dumanlı, tatlımsı ve hafif gül-odunsu; tütsü gibi sıcak.'),
    ('birch|hus+|hus agaci|birch tar|birch leaf', 'Huş: katran gibi dumanlı, derimsi ve isli; Rus derisi kokusunun kaynağı.'),
    ('cashmere wood|cashmeran|kasmir agaci|kasmeran+|cashmirwood|kashmir wood|cashmere woods', 'Kaşmir ağacı (cashmeran): yumuşak, miskli-odunsu ve hafif baharatlı; kazak sıcaklığı.'),
    ('rosewood|gul agaci|bois de rose|ho wood|palisander', 'Gül ağacı: gülümsü, hafif baharatlı ve temiz bir odun.'),
    ('ebony|abanoz+|blackwood|wenge|ebony wood|ebony tree', 'Abanoz: koyu, kuru ve ağır bir odun; ciddi ve derin.'),
    ('oak|mese+|oak tree|oakwood|oak wood', 'Meşe: fıçı gibi; kuru, tanenli ve hafif vanilyalı bir odun.'),
    ('teak|tik agaci|teakwood|mahogany|maun+|mahoganywood|walnut wood|beech|maple|akcaagac+|elm|alder|sycamore|poplar|cottonwood|willow|sogut+|cherry tree|apple tree|pear tree|pear wood|plum tree|plum wood|almond tree|almond wood|olive wood|mango tree|lemon tree|limon agaci|orange tree|cabreuva|boxwood|palm tree|carob tree|baobab|mopane|paperbark|belambra tree|siriuba tree|pink ipe tree|princess tree|paulownia|ginkgo|cork|mesquite wood|mangrove wood|satinwood|cocobolo|tamboti wood|muhuhu|leatherwood|buddha wood|pamplewood|thanaka wood|firwood|wolfwood|healingwood',
     'Ağaç / kereste: kuru, sıcak ve hafif tanenli odun kokusu; mobilya ve gövde hissi.'),
    ('driftwood|deniz odunu', 'Deniz odunu: tuzla ağarmış, kuru ve mineral bir odun.'),
    ('hinoki|hinoki wood|japanese cypress|hiba', 'Hinoki: limonlu, temiz ve tütsümsü Japon selvisi; hamam ferahlığı.'),
    ('nagarmotha|cypriol|cypriol oil|nut grass', 'Nagarmotha (cypriol): topraksı, dumanlı ve deri-odunsu bir kök; ud akorlarının yardımcısı.'),
    ('papyrus|papirus+', 'Papirüs: kuru, odunsu ve hafif yeşil-baharatlı.'),
    ('amyris', 'Amyris: yumuşak, sandalımsı ve hafif reçineli bir odun.'),
    ('akigalawood|akigala agaci|akigala', 'Akigalawood: paçuliden elde edilen modern bir molekül; biberli, odunsu ve temiz.'),
    ('iso e super|timbersilk|georgywood|kephalis|vertofix|sylvamber', 'Iso E Super ailesi: kadifemsi, sedirimsi şeffaf odun molekülü; tende “kendi kokun gibi” yayılır.'),
    ('ambroxan|ambrox|ambrox super|cetalox|ambrofix|orcanox|ambermax|amber xtreme|ambrocenide|norlimbanol|z11|z 11|z 11 hd|ambrostar|amberever|cashalox|ambertonic|ambrinol|trimofix|okoumal|sinfonide|lorenox|dreamwood|mystikal|operanide|amberwood|amber wood|amber agaci|ambermor|aldron|moxalone|toscanol|belanis',
     'Modern amber-odun molekülü: kuru, mineral ve çok kalıcı; parfüme güçlü bir iz ve yayılım verir.'),
    ('javanol|sandalore|ebanol|polysantol|dartanol|bacdanol', 'Sentetik sandal molekülü: kremsi, güçlü ve çok kalıcı bir sandal ağacı etkisi.'),
    ('clearwood', 'Clearwood: paçulinin temiz, topraksız modern hali; yumuşak ve odunsu.'),
    # resins, smoke, leather
    ('incense|tutsu+|olibanum|frankincense|gunluk+|bakhoor|kyphi|nag champa|choya loban|encens', 'Tütsü (günlük): reçineli, limonlu-biberli ve dumanlı; tapınak dinginliği.'),
    ('myrrh|mur+|myrrhe', 'Mür: acımsı, reçineli ve hafif mantarımsı; koyu ve mistik.'),
    ('opoponax|opoponaks+|sweet myrrh', 'Opoponaks: tatlı mür; ballı, balsamik ve pudralı bir sıcaklık.'),
    ('benzoin+|benjoin', 'Benzoin: vanilyalı, tarçınlı ve reçineli tatlı bir balsam; sarmalayıcı bir sıcaklık.'),
    ('labdanum+|cistus|rock rose|ladanum|cistus incanus|ciste', 'Labdanum: deri, bal ve amber kokan yoğun bir reçine; amber akorunun kalbi.'),
    ('elemi|elemi recinesi', 'Elemi: limonlu, biberli ve çamsı ferah bir reçine.'),
    ('styrax|storax|sigla+|liquidambar', 'Sığla (styrax): deri, tarçın ve duman kokan bir balsam.'),
    ('tolu|tolu balsam+|peru balsam+|balsam of peru|tolu balsami|peru balsami', 'Peru / tolu balsamı: vanilyalı, tarçınlı ve hafif dumanlı tatlı bir balsam.'),
    ('mastic|sakiz+|lentisque|lentisk', 'Sakız (damla sakızı): yeşil, çamsı ve hafif reçineli bir ferahlık.'),
    ('balsam|balsami|resin|recine+|copaiba|copaiba balm|copahu balm|gurjun balsam|gurjan balsami|copal|breu branco|dragon blood resin|propolis|wood resin|siam resin|canadian balsam|egyptian balsam|balsamic|balsamik+|balsamic notes',
     'Reçine / balsam: ılık, tatlımsı ve yapışkan-odunsu; parfümü sabitler ve sıcaklık verir.'),
    ('amber|kehribar+|ambre|light amber|ambreine|amber oil|ambrarome', 'Amber: labdanum, vanilya ve benzoin karışımı sıcak, tatlı ve reçineli bir akor.'),
    ('ambergris|amber baligi|ambre gris|grey amber', 'Ambergris (amber balığı): tuzlu, tenimsi ve hafif tatlı bir deniz kokusu; yayılımı artırır.'),
    ('smoke|duman+|smoky notes|ash|kul+|ember|fire|ates+|charcoal|coal|soot|tar|katran+|cade|cade oil|gunpowder|barut+|burnt match|charred wood|coal tar|pine tar|creosote bush|guaiacol|bbq|campfire|oud smoke',
     'Duman / is: yanık odun, kül ve katran; parfüme sertlik ve derinlik verir.'),
    ('leather|deri+|suede|suet+|cuir|saffiano leather|suederal|russian leather|white suede|alcantara accord', 'Deri: sıcak, hayvansı-dumanlı ve lüks; süet daha yumuşak ve kadifemsidir.'),
    # musks, animalics, skin
    ('musk|misk+|muscone|muscenone|galaxolide|habanolide|helvetolide|ambrettolide|sylkolide|serenolide|romandolide|exaltolide|cosmone|velvione|tonalide|ambrette|musk mallow|ambretone|muguet musk',
     'Misk: temiz, yumuşak ve ten gibi sıcak; diğer notaları tutar, kalıcılığı artırır.'),
    ('civet|misk kedisi|civetta|civettone|synthetic civet', 'Civet (misk kedisi): hayvansı, sıcak ve hafif kirli; bugün sentetiktir, çiçeklere derinlik verir.'),
    ('castoreum|kastoreum+|hyrax|hyraceum', 'Kastoreum / hyrax: derimsi, dumanlı ve hayvansı; eski usul sıcak bir taban.'),
    ('animalic|animal notes|hayvansi notalar|hayvansi|fur|indole|skatole|sweat|goat hair tincture|costus', 'Hayvansı not: sıcak, tenimsi ve hafif kirli; parfüme canlılık ve şehvet katar.'),
    ('skin|ten akoru|skin musk|salty skin', 'Ten akoru: temiz, sıcak cilt kokusu; miskli ve hafif tuzlu.'),
    ('beeswax|balmumu+|wax|honeycomb|candle wax', 'Balmumu: ballı, mumsu ve hafif tütünsü bir sıcaklık.'),
    ('honey|bal+|miel|black locust honey|white mimosa honey', 'Bal: yoğun, tatlı ve hafif hayvansı-mumsu; sıcak ve çekici.'),
    # gourmand
    ('chocolate|cikolata+|cocoa|cacao|kakao+|gianduia|nutella|chocolate truffle|cocoa shell|kakao kabugu|cacao butter|hot chocolate|chocolate fudge|chocolate sauce|hazelnut cocoa spread|cocoapulse',
     'Çikolata / kakao: koyu, hafif acı ve tozlu-tatlı; sıcak ve iştah açıcı.'),
    ('coffee|kahve+|espresso|cappuccino|mocha|macchiato|caffe latte|kopi luwak coffee|affogato|cafe expresso|coffee bean|roasted coffee beans|turkish coffee beans',
     'Kahve: kavrulmuş, acımsı ve sıcak; enerji ve derinlik katar.'),
    ('caramel|karamel+|toffee|tofi+|butterscotch|dulce de leche|fudge|burnt sugar|brown sugar|esmer seker+|molasses|maple syrup|salted caramel|daim|palm sugar|creme brulee|canele',
     'Karamel: yanık şeker; tereyağlı, sıcak ve yoğun bir tatlılık.'),
    ('praline|pralin+|nougat|dragee|confetti sugared almonds|calissons d aix|halva|helva+', 'Pralin: karamelize fındık-badem; tatlı, kavrulmuş ve kremsi.'),
    ('marshmallow|chamallow|zefir|marshamallow|squishmallow accord', 'Marshmallow: pudralı, vanilyalı ve bulut gibi yumuşak bir şeker.'),
    ('cotton candy|pamuk seker+|spun sugar|maltol|ethyl maltol|candy floss|coton candy', 'Pamuk şeker: karamelimsi, meyveli ve havadar; ethyl maltol molekülünün yoğun şeker kokusu.'),
    ('bubble gum|bubblegum|balonlu sakiz|bubbaloo', 'Balonlu sakız: meyveli, şekerli ve çocuksu.'),
    ('sugar|seker+|candy|candies|bonbon|sweet notes|tatli notalar|^glace|boba|^syrup|^surup+|icing|frosting|sprinkles|jelly|jellybean|gummy candies|lokum+|loukhoum|macaron|meringue|sugar cane|seker kamisi|powdered sugar|sugar syrup|vanilla sugar|candy apple|sweets|dragibus|starburst candy|tanghulu',
     'Şeker akoru: saf tatlılık; meyveli ya da vanilyalı bir şekerleme hissi.'),
    ('^milk|^sut+|^cream|^krema+|milk cream|krem santi|creamy notes|lactones|lactonic|condensed milk|yogurt|^butter|salted butter|tereyagi+|chantilly cream|whipped cream|mascarpone cheese|cheesecake|custard|panacotta|panna cotta|pudding|milkshake|ice cream|dondurma+|gelato|kulfi|milk mousse|fior di latte|goat s milk|creamsicle|buttercream|sweet milk|fresh cream|sour cream|buttermilk|frothed milk|vanilla sauce',
     'Süt / krema: yumuşak, tatlımsı ve sarmalayıcı; parfüme kadifemsi bir doku verir.'),
    ('almond|badem+|marzipan|amaretto|bitter almond|aci badem+|sweet almond|green almond', 'Badem: tatlı-acı; marzipan ve kiraz çekirdeği kokusu, pudralı ve sıcak.'),
    ('pistachio|antep fistigi|fistik+|pistache', 'Antep fıstığı: yeşil, tatlı-tuzlu ve kremsi bir kuruyemiş; son yılların gözde gurme notası.'),
    ('hazelnut|findik+|findigi|walnut|ceviz+|peanut|peanut butter|pecan|macadamia|cashew|chestnut|kestane+|marron glace|brazil nut|nut|nutty notes|kuruyemis+|roasted nuts|acorn|shea nuts',
     'Kuruyemiş: kavrulmuş, yağlı ve tatlımsı; gurme parfümlere sıcak bir doku katar.'),
    ('cake|kek+|cookie|biscuit|biskuvi+|bread|ekmek+|ekmegi|croissant|brioche|waffle|cone waffle|pancake|pie|tart|donut|doughnut|dough|cookie dough|pastry|pastries|puff pastry|madeleine|baklava|tiramisu|crumble|wafer|panettone|cupcake|toast|popcorn|gingerbread|biscotti|speculoos|graham crackers|sacher torte|shortcrust pastry|baguette|pretzel|knafeh|mochi|dorayaki|churros|souffle|baba|pastiera napoletana|tropezienne tarte|fougassette|tartine|rice cake|apple pie|lemon pie|lemon meringue pie|coconut pie',
     'Fırın / hamur işi: tereyağlı, vanilyalı ve sıcak; taze pişmiş tatlı kokusu.'),
    ('rice|pirinc+|basmati|rice basmati|rice powder|rice pudding|toasted rice|rice water|rice milk|horchata', 'Pirinç: buharlı, sütlü ve hafif pudralı; temiz ve yumuşak.'),
    ('cereals|cereal|wheat|bugday+|oat|yulaf+|barley|malt|corn|bran|rye|grains|flour|un+|buckwheat|soybean|soy milk|oatmilk|yeast', 'Tahıl: kuru, hafif fındıksı ve sıcak; un ve ekmek kabuğu hissi.'),
    ('ice|buz+|frost|snow|kar+|glacier', 'Buz / kar: serin, şeffaf ve mineral; mentol ve su notalarıyla yaratılan bir soğukluk hissi.'),
    # drinks
    ('rum|=rom|rhum|cachaca|rhum agricole|white rum|buttered rum|coconut rum', 'Rom: şeker kamışı, karamel ve fıçı; sıcak, tatlı ve keyifli.'),
    ('whisky|whiskey|viski+|bourbon whiskey|scotch', 'Viski: fıçı, malt ve duman; sıcak, odunsu bir içki notası.'),
    ('cognac|konyak+|brandy|armagnac|calvados|calvados drink|eau de vie', 'Konyak: kuru meyve, fıçı ve vanilya kokan sıcak bir üzüm brendisi.'),
    ('wine|sarap+|sarabi|champagne|sampanya+|prosecco|sparkling wine|port wine|sherry|vermouth|sangria|mulled wine|red wine|white wine|champagne rose|wine lees|wine must|tokaji wine|madeira|kir royal|plum wine|sake',
     'Şarap / şampanya: üzümlü, hafif ekşi; köpüklü ya da tanenli bir içki havası.'),
    ('vodka|votka+|tequila|mezcal|liquor|liqueur|likor+|boozy notes|alcohol|cocktail|kokteyl+|mojito|margarita|blue margarita|daiquiri|pina colada|bellini|negroni|aperol|campari|martini|punch|tonic water|lemonade|beer|bira+|beer ale|moscow mule|cosmopolitan cocktail|caipirinha|pisco sour cocktal|curacao|amarula|baileys irish cream|advocaat|limonata+|cream soda|lemon soda|orange soda|sparkling water|almdudler|cream liqueur|coffee liqueur',
     'İçki / kokteyl akoru: alkolün sıcaklığı ile meyve ve şekerin karışımı; parti havası verir.'),
    ('cola|coca cola|kola+', 'Kola: tarçınlı, limonlu ve karamelli köpüklü içecek kokusu.'),
    # water, air, minerals
    ('sea|deniz+|marine|marine notes|ocean|okyanus+|aquatic|aquatic notes|water notes|su notalari|calone|sea water|deniz suyu|ozonic|ozonic notes|ozonik notalar|ozon+|aqua|watery notes|rain|rain notes|yagmur+|dew|dew drop|ciy+|river notes|head space waterfall|aquozone|cascalone|calypsone|floralozone|aqual|sea foam|^water|water fruit|sea notes|deniz notalari|thalassogaia|steam accord|holy water',
     'Su / deniz notaları: serin, tuzlu ya da ıslak; kavunumsu-ozonik bir temizlik hissi verir.'),
    ('salt|tuz+|sea salt|deniz tuzu|pink himalayan sea salt|salty notes', 'Tuz: mineral, kuru ve tenimsi; denizden çıkmış cilt hissi.'),
    ('earth|earthy notes|toprak+|topragi|soil|soil tincture|petrichor|geosmin|mud|dirt|peat|mitti attar|beetroot|roots|clay|kil+|terracotta|desert rain accord',
     'Toprak: yağmur sonrası ıslak toprak, kök ve pancar kokusu; koyu ve doğal.'),
    ('mineral notes|mineral|stone|tas+|flint|cakmak tasi|pebbles|slate|concrete|beton+|chalk|graphite|wet stone|sand|kum+|lava|cobblestone|coral reef|coral limestone|wet plaster|asphalt|dust|toz+|sulphur',
     'Mineral not: ıslak taş, çakmak taşı ya da kum; serin, kuru ve temiz.'),
    ('metallic notes|metalik notalar|metal|metallic|aluminum|steel|iron|hot iron|blood|kan+|sp3 carbon', 'Metalik not: soğuk, keskin ve parlak; bıçak ağzı ya da madeni para hissi.'),
    ('air|hava+|airy note|fresh air|mountain air|wind|ruzgar+|oxygen|ozone|fresh note|clean notes|airy notes', 'Hava / ozon: temiz, serin ve ferah; açık hava ve yeni yıkanmış çamaşır hissi.'),
    ('aldehyde|aldehit+|dodecanal|aldehydic', 'Aldehitler: sabunsu, mumsu ve köpüklü bir parlaklık; Chanel No 5 etkisi.'),
    ('solar notes|gunes notalari|sun|solar|suntan lotion|sunscreen|amyl salicylate|salicylic acid|salicylates|sunny notes', 'Güneş notaları: ılık ten, güneş kremi ve tuz; salisilatlarla yaratılan bir tatil hissi.'),
    ('powder|pudra+|powdery notes|pudrali notalar|talc|makeup|lipstick|ruj+|lip gloss|rice powder|white powder|hand cream|cosmetic', 'Pudralı not: yumuşak, kuru ve makyaj çantası gibi; iris, menekşe ve misk ile kurulur.'),
    ('soap|sabun+|laundry|linen|keten+|cotton|pamuk+|pamugu|fabric|fresh linen|detergent|shampoo|t shirt accord|clean cotton', 'Temiz / sabunsu not: yeni yıkanmış çamaşır, sabun köpüğü ve pamuk hissi.'),
    ('hedione|paradisone|jasmone|jasmolactone', 'Hedione: havadar, limonlu bir yasemin molekülü; parfüme ışık, ferahlık ve yayılım verir.'),
    ('dihydromyrcenol', 'Dihydromyrcenol: narenciyeli-lavantalı, metalik bir temizlik; 90’ların ferah erkek parfümü kokusu.'),
    ('pomarose|damascone|rose oxide|rhodinol|rosyfolia|petalia|peonile|mahonial|florol|lilial|nympheal|hivernal|starfleur|karmaflor|mugane|lysylang|veloutone|bisabolene|hexyl acetate|cosmofruit|pearadise|physcool|naturalcalm|scent trek|antillone|osmasylk natsublim',
     'Koku molekülü: laboratuvarda üretilen şeffaf, temiz bir çiçek ya da meyve etkisi; doğal notaları parlatır.'),
    ('ionone|ionones', 'İyononlar: menekşe ve iris kokusunu veren pudralı-odunsu moleküller.'),
    # materials, places, oddities
    ('vinyl|plastic|rubber|kaucuk+|latex|caoutchouc|gasoline|benzin+|petroleum|motor oil|spray paint|industrial glue|nail polish|neoprene|ink|murekkep+|paper|kagit+|old books|pencil|parchment|canvas|varnish accord|tennis ball|plastic bag|brown scotch tape|party balloons|play doh|credit cards|instant film accord|diving suit|surf wax|isobutyl quinoline',
     'Endüstriyel / sıra dışı not: plastik, mürekkep ya da benzin gibi kokular; parfüme modern, şaşırtıcı bir karakter verir.'),
    ('mushroom|mantar+|truffle|truf+|cep|boletus edulis', 'Mantar / trüf: nemli, topraksı ve umami; orman zemini derinliği.'),
    ('caviar|havyar+|oyster|fish|seashell|starfish|pearls', 'Deniz ürünü / kabuk: tuzlu, iyotlu ve mineral; kıyı havası.'),
    ('velvet|kadife+|silk|ipek+|ipegi|satin|cashmere|kasmir+|wool|yun+|lace|jeans|fur accord|velvet woods', 'Kumaş hissi: gerçek bir koku değil, doku anlatımı; yumuşak, miskli ve sarmalayıcı.'),
    ('crystal|diamond|black diamond|gold|altin+|stardust|pink crystal|blue crystal|glass|porcelain|money|space ship|powder from the moon|factor x|poison|cocaine|opium|flower prism|sparkling accord|sauna|old furniture|old house|priest s clothes|red lantern|floratta dna|tatami',
     'Fantezi not: gerçek bir hammaddesi yok; parfümcünün ışıltı, lüks ya da soğukluk hissini anlatma biçimi.'),
    ('cactus|kaktus+|aloe vera|agave|cactus flower|cactus juice|succulent|snake plant|sansevieria', 'Kaktüs / aloe: sulu, yeşil ve serin; çöl bitkisinin ferah özü.'),
    ('pumpkin|bal kabagi|squash|zucchini|potato|cauliflower|spinach|artichoke|pea|bean|red beans|mung bean|garlic|sarimsak+|daikon radish|bitter melon|chayote|pesto|tomato sauce|pizza|bacon|meat|cheese|peynir+|salted egg yolk|pisto',
     'Mutfak notası: sebze ya da yemek kokusu; parfümde şaşırtmak ve doğallık katmak için kullanılır.'),
]

# asked only when no material was found
GENERIC = [
    ('oriental notes|oryantal notalar|oriental|oriental woodsy notes|oriental flower notes', 'Oryantal akor: amber, vanilya, reçine ve baharat; sıcak, tatlı ve yoğun.'),
    ('chypre notes|chypre|sipre+', 'Şipre akoru: bergamot, meşe yosunu ve labdanum; kuru, zarif ve yosunlu.'),
    ('gourmand accord|gourmand|gurme+|gourmand notes', 'Gurme akor: yenilebilir tatlılar; vanilya, karamel ve çikolata hissi.'),
    ('fougere accord', 'Fougère akoru: lavanta, meşe yosunu ve kumarin; klasik berber temizliği.'),
    ('fruit|fruity notes|meyve+|meyveli notalar|fruity|yellow fruits|juicy notes', 'Meyveli akor: tatlı, sulu ve neşeli bir hava verir.'),
    ('flower|floral notes|cicek+|cicegi|ciceksi notalar|blossom|bloom|floral|petal|bouquet|floral bouquet|wildflowers|transparent flowers|yellow flowers|flowers', 'Çiçeksi akor: yumuşaklık, tazelik ya da romantik bir hava katar.'),
    ('wood|woods|woody notes|odun+|odunsu notalar|agac+|agaci|agaclar|bois|bark|woodsy notes|woody|dry wood|white wood|exotic woods|blonde woods|transparent woods|precious woods|degerli agaclar|beyaz agaclar|trees|tree',
     'Odunsu not: kuru, sıcak ve ahşap hissi verir; genelde tabanda kalıcılık sağlar.'),
    ('spice|spices|baharat+|baharatli notalar|spicy notes|spicy|aromatic spices|exotic spices|baking spices|indian spices|arabian spices', 'Baharat akoru: sıcaklık ve canlılık verir; tarçın, karanfil ve biber karışımı.'),
    ('green notes|yesil notalar|green accord|greens|stems greens|sap|green sap|chlorophyll|foliage|forest foliage|leaf|leaves|yaprak+|yapragi|yapraklar|green branches|vine|green forest|herbal notes|bitkisel notalar|aromatic notes|aromatik notalar|herbs|=ot|otu|otlar|green|fresh evergreen',
     'Yeşil / aromatik not: kesilmiş çimen, yaprak ve ot kokusu; tazelik ve doğallık verir.'),
    ('nectar|juice|jam|marmalade|recel+|compote|sorbet|smoothie|fruit tea|chutney', 'Meyve tatlısı: şurup, reçel ya da sorbe gibi; sulu, şekerli ve yoğun bir meyve hissi.'),
    ('accord|notes|notalar|akor+|akoru|essence|extract|co2 extracts|oily notes', 'Akor: tek bir hammadde değil, birkaç notanın birlikte yarattığı bir koku etkisi.'),
]

# what is left of the name after its material
QUALS = [
    ('candied|sekerlenmis|glace|crystallized|sugared', '“Şekerlenmiş” hali şurupta bekletilmiş gibi daha yoğun, reçelimsi ve tatlıdır.'),
    ('caramelized|karamelize', 'Karamelize hali yanık şeker tatlılığı taşır.'),
    ('blossom|flower|cicegi|bloom|petals', 'Çiçeği daha narin, ballı ve hafif pudralıdır.'),
    ('leaf|leaves|yapragi|yapraklari', 'Yaprağı daha yeşil, taze ve hafif acımsıdır.'),
    ('peel|zest|rind|kabugu', 'Kabuğu daha keskin, acımsı ve yağlıdır.'),
    ('seed|seeds|tohumu', 'Tohumu daha kuru, baharatlı ve topraksıdır.'),
    ('root|koku', 'Kökü daha topraksı ve derindir.'),
    ('bud|buds|tomurcugu', 'Tomurcuğu daha yeşil ve keskindir.'),
    ('absolute|absolu|extract|essence|oil|tincture|co2|yagi', 'Absolü / yağ hali doğal özütün daha yoğun ve derin kokusudur.'),
    ('water|suyu', 'Su hali daha hafif, şeffaf ve serindir.'),
    ('milk|sutu', 'Sütü kremsi, yumuşak ve hafif tatlıdır.'),
    ('cream|krema|kremasi|creamy', 'Krema hali daha yumuşak, sütlü ve tatlıdır.'),
    ('nectar|juice|juicy|syrup', 'Nektar / şurup hali daha sulu, tatlı ve yoğundur.'),
    ('jam|marmalade|compote|receli', 'Reçel hali pişmiş, yoğun ve şekerlidir.'),
    ('liqueur|liquor|likoru', 'Likör hali alkolün sıcaklığıyla daha tatlı ve yoğundur.'),
    ('wild|yabani', 'Yabani türü daha yeşil, keskin ve doğaldır.'),
    ('white|beyaz', 'Beyaz türü daha temiz, hafif ve yumuşaktır.'),
    ('black|siyah|kara|dark|koyu', 'Siyah / koyu türü daha derin ve yoğundur.'),
    ('pink|pembe', 'Pembe türü daha tatlı, narin ve hafiftir.'),
    ('red|kirmizi', 'Kırmızı türü daha olgun, sıcak ve yoğundur.'),
    ('green|yesil', 'Yeşil hali daha ham, taze ve keskindir.'),
    ('bitter|aci', 'Acı türü daha kuru, keskin ve bademsidir.'),
    ('dried|dry|kuru', 'Kurutulmuş hali daha yoğun ve koyudur.'),
    ('frosted|iced|frozen|buzlu', 'Buzlu yorumu mentol ve su notalarıyla serinletilmiştir.'),
    ('roasted|toasted|kavrulmus|grilled', 'Kavrulmuş hali daha sıcak, fındıksı ve hafif islidir.'),
    ('burnt|burning|yanik|smoked|smoky|isli', 'İsli / yanık hali duman ve kömür dokunuşu taşır.'),
    ('salted|tuzlu', 'Tuzlu hali tatlılığı dengeleyen mineral bir dokunuş taşır.'),
    ('sparkling|kopuklu|fizzy', 'Köpüklü yorumu gazlı içecek canlılığı verir.'),
]

ORIGINS = [
    ('sicilian|sicilya', 'Sicilya'), ('calabrian|kalabriya', 'Kalabriya'), ('italian|italyan', 'İtalya'), ('amalfi', 'Amalfi'), ('tuscan', 'Toskana'),
    ('french|fransiz', 'Fransa'), ('grasse', 'Grasse'), ('spanish|ispanyol', 'İspanya'), ('moroccan|fas', 'Fas'), ('tunisian|tunus', 'Tunus'),
    ('egyptian|misir', 'Mısır'), ('algerian', 'Cezayir'), ('turkish|turkey|turk', 'Türkiye'), ('bulgarian|bulgar', 'Bulgaristan'), ('taif', 'Taif'),
    ('iran|persian', 'İran'), ('indian|hint', 'Hindistan'), ('mysore', 'Mysore'), ('himalayan', 'Himalaya'), ('ceylon|seylan', 'Seylan'),
    ('indonesian|endonezya', 'Endonezya'), ('java', 'Cava'), ('singapore', 'Singapur'), ('malaysian', 'Malezya'), ('thailand|siam|siyam', 'Tayland'),
    ('laotian', 'Laos'), ('cambodian', 'Kamboçya'), ('vietnamese', 'Vietnam'), ('chinese|=cin', 'Çin'), ('japanese|japon', 'Japonya'),
    ('madagascar|madagaskar', 'Madagaskar'), ('bourbon', 'Bourbon (Réunion adası)'), ('tahitian|tahiti', 'Tahiti'), ('haitian|haiti', 'Haiti'),
    ('brazilian|brezilya', 'Brezilya'), ('paraguay', 'Paraguay'), ('argentinian', 'Arjantin'), ('mexican|meksika', 'Meksika'), ('guatemalan', 'Guatemala'),
    ('peruvian', 'Peru'), ('texas', 'Teksas'), ('virginian|virginia', 'Virginia'), ('californian|california', 'Kaliforniya'), ('florida', 'Florida'),
    ('canadian', 'Kanada'), ('hawaiian', 'Hawaii'), ('australian|avustralya', 'Avustralya'), ('african|afrika', 'Afrika'), ('somalian', 'Somali'),
    ('nigerian', 'Nijerya'), ('siberian|sibirya', 'Sibirya'), ('serbian', 'Sırbistan'), ('georgian', 'Gürcistan'), ('israeli', 'İsrail'),
    ('assam', 'Assam'), ('columbian', 'Kolombiya'), ('atlas', 'Atlas Dağları'),
]

# written by hand: names a rule would explain badly
EXACT = {
    'Candied Fruits': 'Şekerlenmiş meyveler: şurupta bekletilip kurutulmuş portakal, kiraz ve kayısı; yoğun, reçelimsi ve yılbaşı pastası gibi tatlı.',
    'Candied Almond': 'Şekerli badem (badem şekeri): karamelize şekerle kaplı kavrulmuş badem; sıcak, tatlı ve hafif tarçınlı.',
    'Candied Orange': 'Portakal şekerlemesi: şurupta pişmiş portakal kabuğu; tatlı, hafif acı ve reçelimsi.',
    'Candied Lemon': 'Limon şekerlemesi: şurupta pişmiş limon kabuğu; ekşiliği gitmiş, tatlı ve parlak.',
    'Candied Ginger': 'Zencefil şekerlemesi: şekerle yumuşamış zencefil; sıcak, tatlı ve hafif yakıcı.',
    'Candied Flowers': 'Şekerlenmiş çiçekler: şekerle kaplı menekşe ve gül yaprağı; pudralı, tatlı ve narin.',
    'Big Strawberry': 'İri çilek: olgun, sulu ve şeker gibi bir çilek akoru; genç ve neşeli.',
    'Mousse de Saxe': 'Mousse de Saxe: eski parfümcülüğün ünlü hazır bazı; koyu, yosunlu-derimsi, anasonlu ve pudralı.',
    'Shamama Attar': 'Şamama attarı: onlarca baharat, ot ve reçineyle yapılan geleneksel Hint yağı; sıcak, baharatlı ve topraksı.',
    'Choya Nakh': 'Choya nakh: kavrulmuş deniz kabuğundan elde edilen Hint özü; dumanlı, derimsi ve isli.',
    'Choya Ral': 'Choya ral: kavrulmuş reçineden elde edilen Hint özü; dumanlı, katranlı ve isli.',
    'Shea Butter': 'Shea yağı: yağlı, fındıksı ve hafif tatlı; cilt kremi yumuşaklığı.',
    'Water': 'Su: serin, şeffaf ve temiz; diğer notaları ferahlatan bir ıslaklık hissi.',
    'Citrus': 'Narenciye akoru: limon, portakal ve bergamot karışımı ferah, parlak bir açılış.',
    'Earthy Notes': 'Topraksı notalar: ıslak toprak, kök ve yosun; koyu, doğal ve hafif nemli.',
    'Sand': 'Kum: güneşte ısınmış, kuru ve mineral; hafif tuzlu bir plaj hissi.',
    'Liquor': 'Likör: alkolün sıcaklığıyla tatlı ve yoğun bir içki notası.',
    'Skin': 'Ten akoru: temiz, sıcak cilt kokusu; miskli ve hafif tuzlu.',
    'Ink': 'Mürekkep: metalik, hafif acı ve serin; kâğıt ve kalem hissi.',
    'Linen': 'Keten: yeni yıkanıp ütülenmiş kumaş; temiz, serin ve pudralı.',
    'Sorbet': 'Sorbe: buzlu, sulu ve şekerli bir meyve tatlısı; serin ve ferah.',
    'Custard': 'Muhallebi kreması: yumurtalı, vanilyalı ve sütlü; yumuşak ve tatlı.',
    'Wheat': 'Buğday: kuru, hafif fındıksı ve sıcak; un ve ekmek kabuğu hissi.',
    'Sour Cherry': 'Vişne: kirazın ekşi, koyu ve likörümsü hali; bademsi bir çekirdek tadı vardır.',
    'Black Cherry': 'Siyah kiraz: olgun, koyu ve likör gibi; tatlı ve hafif bademsi.',
    'Ice cream': 'Dondurma: soğuk, sütlü ve vanilyalı; kremsi bir tatlılık.',
    'Truffle': 'Trüf mantarı: nemli, topraksı ve hafif sarımsaksı; koyu ve lüks bir derinlik.',
    'Tulip': 'Lale: yeşil, sulu ve çok hafif; taze kesilmiş çiçek sapı hissi.',
    'Camphor': 'Kâfur: serin, mentollü ve tıbbi-temiz; nefes açan keskin bir ferahlık.',
    'Clover': 'Yonca: yeşil, ballı ve samansı; çayır kokusu.',
    'Walnut': 'Ceviz: kuru, yağlı ve hafif acımsı bir kuruyemiş; odunsu bir sıcaklık.',
    'Maple': 'Akçaağaç: şurubu karamel ve odun arası; tatlı, sıcak ve hafif dumanlı.',
    'Popcorn': 'Patlamış mısır: tereyağlı, tuzlu-tatlı ve sıcak.',
    'Brandy': 'Brendi: kuru meyve, fıçı ve vanilya kokan sıcak bir üzüm içkisi.',
    'Biscuit': 'Bisküvi: tereyağlı, vanilyalı ve hafif kavrulmuş; sıcak bir fırın kokusu.',
    'Cake': 'Kek: tereyağlı, vanilyalı ve yumuşak; taze pişmiş tatlı kokusu.',
    'Syrup': 'Şurup: yoğun, akışkan ve saf şeker tatlılığı.',
    'Malt': 'Malt: çimlenmiş arpa; bisküvimsi, hafif karamelli ve sıcak.',
    'Mushroom': 'Mantar: nemli, topraksı ve umami; orman zemini kokusu.',
    'Ash': 'Kül: sönmüş ateşin kuru, mineral ve isli kokusu.',
    'Bran': 'Kepek: kuru, tahılsı ve hafif fındıksı.',
    'Mojito': 'Mojito: nane, misket limonu ve rom; serin, ekşi-tatlı bir kokteyl.',
    'Hyrax': 'Hyrax (hyraceum): fosilleşmiş bir hayvansal madde; derimsi, dumanlı ve sıcak.',
    'Datura': 'Datura (boru çiçeği): gece açan, baygın ve hafif narkotik bir beyaz çiçek.',
    'Palmarosa': 'Palmarosa: gül gibi kokan bir ot; taze, limonlu ve hafif yeşil.',
    'Priprioca': 'Priprioca: Amazon kökü; topraksı, odunsu ve hafif baharatlı.',
    'Calamus': 'Calamus (eğir otu): sütlü, derimsi ve baharatlı bir kök.',
    'Costus': 'Costus kökü: hayvansı, yağlı ve saç-kürk gibi sıcak bir kök kokusu.',
    'Buchu or Agathosma': 'Buchu: frenk üzümüne benzeyen keskin, naneli ve kükürtlü bir Güney Afrika bitkisi.',
    'Nard Himalayan (Jatamansi)': 'Hint sümbülü (nard): topraksı, hayvansı ve valerian benzeri eski bir tütsü kökü.',
    'Nard': 'Hint sümbülü (nard): topraksı, hayvansı ve valerian benzeri eski bir tütsü kökü.',
    'Timur': 'Timur biberi: greyfurt gibi narenciyeli, karıncalandıran ferah bir Nepal biberi.',
    'Cin': 'Cin: ardıç meyvesiyle yapılan içki; çamsı, biberli ve ferah.',
    'Sakız': 'Sakız (damla sakızı): yeşil, çamsı ve hafif reçineli bir ferahlık.',
    'Votka': 'Votka: temiz, keskin ve hafif tahılsı bir alkol notası; parfüme serinlik verir.',
    'Havyar': 'Havyar: tuzlu, iyotlu ve yağlı; lüks çağrışımlı bir deniz notası.',
    'Siam': 'Siyam benzoini: vanilyalı, bademli ve reçineli tatlı bir balsam.',
    'Mystikal': 'Mystikal: Givaudan’ın tütsümsü, odunsu ve deri dokulu molekülü.',
    'Mahonial': 'Mahonial: müge ve yasemin etkisi veren şeffaf, temiz bir çiçek molekülü.',
    'Petalia': 'Petalia: şakayık, gül ve liçi kokan taze bir çiçek molekülü.',
    'Calone': 'Calone: kavun ve deniz havası kokan molekül; 90’ların “okyanus” parfümlerinin imzası.',
    'Hedione': 'Hedione: havadar, limonlu bir yasemin molekülü; parfüme ışık, ferahlık ve yayılım verir.',
    'Iso E Super': 'Iso E Super: kadifemsi, sedirimsi şeffaf odun molekülü; tende “kendi kokun gibi” yayılır.',
    'Kumarin': 'Kumarin: tonka fasulyesinin ana molekülü; bademli, samansı ve vanilyalı bir tatlılık.',
    'Hayvansı notalar': 'Hayvansı notalar: sıcak, tenimsi ve hafif kirli; parfüme canlılık ve şehvet katar.',
    'Güneş notaları': 'Güneş notaları: ılık ten, güneş kremi ve tuz; salisilatlarla yaratılan bir tatil hissi.',
    'Değerli ağaçlar': 'Değerli ağaçlar: sandal, gül ağacı ve abanoz gibi yumuşak, pahalı odunların akoru.',
    'Tütsü (günlük)': 'Tütsü (günlük): reçineli, limonlu-biberli ve dumanlı; tapınak dinginliği.',
    'Balmumu': 'Balmumu: ballı, mumsu ve hafif tütünsü bir sıcaklık.',
    'Reçineler': 'Reçineler: benzoin, labdanum ve mür ailesi; ılık, tatlımsı ve yapışkan bir sıcaklık.',
    'Konyak': 'Konyak: kuru meyve, fıçı ve vanilya kokan sıcak bir üzüm brendisi.',
    'Viski': 'Viski: fıçı, malt ve duman; sıcak, odunsu bir içki notası.',
    'Şampanya': 'Şampanya: köpüklü, hafif ekşi ve mayalı; kutlama havası verir.',
    'Duman': 'Duman: yanık odun ve kül; parfüme sertlik ve derinlik verir.',
    'Marshmallow': 'Marshmallow: pudralı, vanilyalı ve bulut gibi yumuşak bir şeker.',
    'Tereyağı': 'Tereyağı: yağlı, sütlü ve hafif tuzlu; fırın ve krema hissi.',
    'Pirinç': 'Pirinç: buharlı, sütlü ve hafif pudralı; temiz ve yumuşak.',
    'Mersin': 'Mersin: yeşil, kâfurlu ve hafif çiçeksi bir Akdeniz çalısı.',
    'Alıç': 'Alıç çiçeği: bademli, pudralı ve hafif anasonlu; yumuşak bir bahar çiçeği.',
    'Kenevir': 'Kenevir: yeşil, reçineli ve hafif tatlı otsu koku.',
    'Çimen': 'Çimen: taze kesilmiş, sulu ve yeşil; açık hava hissi.',
    'Sarmaşık': 'Sarmaşık: serin, ıslak ve koyu yeşil yaprak kokusu.',
    'Pelin otu': 'Pelin otu: acı-yeşil, anasonlu ve keskin; absinthe havası.',
    'Kuru ot': 'Kuru ot (saman): ballı, tütünsü ve güneşte kurumuş çayır kokusu.',
    'Limon otu': 'Limon otu: limon gibi ama daha otsu ve keskin; ferah, temiz bir yeşillik.',
    'Köknar balsamı': 'Köknar balsamı: reçineli, tatlımsı ve reçelimsi bir çam kokusu; kış ormanı.',
    'Tolu balsamı': 'Tolu balsamı: vanilyalı, tarçınlı ve hafif dumanlı tatlı bir balsam.',
    'Tik ağacı': 'Tik ağacı: kuru, derimsi ve hafif dumanlı sert bir odun.',
    'Gül ağacı': 'Gül ağacı: gülümsü, hafif baharatlı ve temiz bir odun.',
    'Misk kedisi': 'Civet (misk kedisi): hayvansı, sıcak ve hafif kirli; bugün sentetiktir, çiçeklere derinlik verir.',
    'Deniz odunu': 'Deniz odunu: tuzla ağarmış, kuru ve mineral bir odun.',
    'Akigala ağacı': 'Akigalawood: paçuliden elde edilen modern bir molekül; biberli, odunsu ve temiz.',
    'Beyaz ağaçlar': 'Beyaz ağaçlar: huş ve sedir gibi açık renkli, temiz ve kuru odunların akoru.',
    'Çiçekler': 'Çiçek akoru: yumuşaklık, tazelik ya da romantik bir hava katar.',
    'Meyveler': 'Meyve akoru: tatlı, sulu ve neşeli bir hava verir.',
}


def main():
    exact = {}
    if os.path.exists(OLD):
        exact.update({k.strip(): v for k, v in json.load(open(OLD, encoding='utf-8')).items()})
    else:
        exact.update(json.load(open(OUT, encoding='utf-8')).get('exact', {}))
    exact.update(EXACT)
    for spec, _ in HEADS + GENERIC + QUALS + ORIGINS: re.compile(rx(spec))
    data = {
        'v': 2,
        'exact': exact,
        'heads': [[rx(s), t] for s, t in HEADS],
        'generic': [[rx(s), t] for s, t in GENERIC],
        'quals': [[rx(s), t] for s, t in QUALS],
        'origins': [[rx(s), t] for s, t in ORIGINS],
        'tm': 'Parfüm evlerine özel bir koku molekülü ya da akor; üreticisinin tescilli adıyla anılır ve tam olarak neye benzediği açıklanmaz.',
        'unknown': 'Bu ad için hazır bir açıklama yok; büyük olasılıkla parfümcünün verdiği özel bir ad. Aşağıdaki parfümlerde nasıl koktuğunu deneyebilirsin.',
    }
    json.dump(data, open(OUT, 'w', encoding='utf-8'), ensure_ascii=False, separators=(',', ':'))
    print(len(exact), 'exact,', len(HEADS), 'heads,', len(GENERIC), 'generic ->', OUT, os.path.getsize(OUT), 'bytes')


if __name__ == '__main__':
    main()
